name: scraping-script
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install requests tabulate pandas
      - name: Run script
        run: python main.py
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Changes to FCC filings"